-- MySQL Script generated by MySQL Workbench
-- Mon 27 Jul 2015 09:53:08 AM EDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema discoursedb_v02
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `discoursedb_v02` ;

-- -----------------------------------------------------
-- Schema discoursedb_v02
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `discoursedb_v02` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
SHOW WARNINGS;
USE `discoursedb_v02` ;

-- -----------------------------------------------------
-- Table `discoursedb_v02`.`Annotation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discoursedb_v02`.`Annotation` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `discoursedb_v02`.`Annotation` (
  `idAnnotation` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idAnnotation`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `discoursedb_v02`.`Discourse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discoursedb_v02`.`Discourse` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `discoursedb_v02`.`Discourse` (
  `idDiscourse` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Annotation_idAnnotation` BIGINT UNSIGNED NULL,
  `name` VARCHAR(200) NOT NULL,
  `source` VARCHAR(200) NULL,
  PRIMARY KEY (`idDiscourse`),
  CONSTRAINT `fk_Discourse_Annotation1`
    FOREIGN KEY (`Annotation_idAnnotation`)
    REFERENCES `discoursedb_v02`.`Annotation` (`idAnnotation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Discourse_Annotation1_idx` ON `discoursedb_v02`.`Discourse` (`Annotation_idAnnotation` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `discoursedb_v02`.`DiscoursePart_Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discoursedb_v02`.`DiscoursePart_Type` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `discoursedb_v02`.`DiscoursePart_Type` (
  `idDiscoursePart_Type` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`idDiscoursePart_Type`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `discoursedb_v02`.`DiscoursePart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discoursedb_v02`.`DiscoursePart` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `discoursedb_v02`.`DiscoursePart` (
  `idDiscoursePart` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `DiscoursePart_Type_idDiscoursePart_Type` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(200) NULL,
  `startTime` DATETIME NULL COMMENT '	',
  `endTime` DATETIME NULL,
  `Annotation_idAnnotation` BIGINT UNSIGNED NULL,
  PRIMARY KEY (`idDiscoursePart`, `DiscoursePart_Type_idDiscoursePart_Type`),
  CONSTRAINT `fk_DiscoursePart_DiscoursePart_Type1`
    FOREIGN KEY (`DiscoursePart_Type_idDiscoursePart_Type`)
    REFERENCES `discoursedb_v02`.`DiscoursePart_Type` (`idDiscoursePart_Type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DiscoursePart_Annotation1`
    FOREIGN KEY (`Annotation_idAnnotation`)
    REFERENCES `discoursedb_v02`.`Annotation` (`idAnnotation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_DiscoursePart_DiscoursePart_Type1_idx` ON `discoursedb_v02`.`DiscoursePart` (`DiscoursePart_Type_idDiscoursePart_Type` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_DiscoursePart_Annotation1_idx` ON `discoursedb_v02`.`DiscoursePart` (`Annotation_idAnnotation` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `discoursedb_v02`.`Content`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discoursedb_v02`.`Content` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `discoursedb_v02`.`Content` (
  `idRevision` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `creationTime` DATETIME NULL,
  `previousRevisionID` BIGINT UNSIGNED NULL,
  `nextRevisionID` BIGINT UNSIGNED NULL,
  `text` TEXT NULL,
  `data` BLOB NULL,
  `Annotation_idAnnotation` BIGINT UNSIGNED NULL,
  PRIMARY KEY (`idRevision`),
  CONSTRAINT `fk_Revision_Revision1`
    FOREIGN KEY (`previousRevisionID`)
    REFERENCES `discoursedb_v02`.`Content` (`idRevision`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Revision_Revision2`
    FOREIGN KEY (`nextRevisionID`)
    REFERENCES `discoursedb_v02`.`Content` (`idRevision`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Content_Annotation1`
    FOREIGN KEY (`Annotation_idAnnotation`)
    REFERENCES `discoursedb_v02`.`Annotation` (`idAnnotation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Revision_Revision1_idx` ON `discoursedb_v02`.`Content` (`previousRevisionID` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Revision_Revision2_idx` ON `discoursedb_v02`.`Content` (`nextRevisionID` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Content_Annotation1_idx` ON `discoursedb_v02`.`Content` (`Annotation_idAnnotation` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `discoursedb_v02`.`Contribution_Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discoursedb_v02`.`Contribution_Type` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `discoursedb_v02`.`Contribution_Type` (
  `idContribution_Type` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(200) NULL,
  PRIMARY KEY (`idContribution_Type`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `discoursedb_v02`.`Contribution`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discoursedb_v02`.`Contribution` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `discoursedb_v02`.`Contribution` (
  `idContribution` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstRevisionID` BIGINT UNSIGNED NOT NULL,
  `currentRevisionID` BIGINT UNSIGNED NOT NULL,
  `Contribution_Type_idContribution_Type` BIGINT UNSIGNED NOT NULL,
  `startTime` DATETIME NOT NULL,
  `endTime` DATETIME NULL,
  `Annotation_idAnnotation` BIGINT UNSIGNED NULL,
  PRIMARY KEY (`idContribution`),
  CONSTRAINT `fk_Contribution_Revision1`
    FOREIGN KEY (`currentRevisionID`)
    REFERENCES `discoursedb_v02`.`Content` (`idRevision`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contribution_Revision3`
    FOREIGN KEY (`firstRevisionID`)
    REFERENCES `discoursedb_v02`.`Content` (`idRevision`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contribution_Contribution_Type1`
    FOREIGN KEY (`Contribution_Type_idContribution_Type`)
    REFERENCES `discoursedb_v02`.`Contribution_Type` (`idContribution_Type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contribution_Annotation1`
    FOREIGN KEY (`Annotation_idAnnotation`)
    REFERENCES `discoursedb_v02`.`Annotation` (`idAnnotation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Contribution_Revision1_idx` ON `discoursedb_v02`.`Contribution` (`currentRevisionID` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Contribution_Revision3_idx` ON `discoursedb_v02`.`Contribution` (`firstRevisionID` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Contribution_Contribution_Type1_idx` ON `discoursedb_v02`.`Contribution` (`Contribution_Type_idContribution_Type` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Contribution_Annotation1_idx` ON `discoursedb_v02`.`Contribution` (`Annotation_idAnnotation` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `discoursedb_v02`.`DiscourseRelation_Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discoursedb_v02`.`DiscourseRelation_Type` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `discoursedb_v02`.`DiscourseRelation_Type` (
  `idDiscourseRelation_Type` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(200) NULL,
  PRIMARY KEY (`idDiscourseRelation_Type`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `discoursedb_v02`.`DiscourseRelation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discoursedb_v02`.`DiscourseRelation` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `discoursedb_v02`.`DiscourseRelation` (
  `idDiscourseRelation` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sourceContributionId` BIGINT UNSIGNED NOT NULL,
  `targetContributionId` BIGINT UNSIGNED NOT NULL,
  `discourseRelation_TypeID` BIGINT UNSIGNED NOT NULL,
  `startTime` DATETIME NULL,
  `endTime` DATETIME NULL,
  `Annotation_idAnnotation` BIGINT UNSIGNED NULL,
  PRIMARY KEY (`idDiscourseRelation`),
  CONSTRAINT `fk_Reply_Contribution1`
    FOREIGN KEY (`sourceContributionId`)
    REFERENCES `discoursedb_v02`.`Contribution` (`idContribution`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reply_Contribution2`
    FOREIGN KEY (`targetContributionId`)
    REFERENCES `discoursedb_v02`.`Contribution` (`idContribution`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reply_Reply_Type1`
    FOREIGN KEY (`discourseRelation_TypeID`)
    REFERENCES `discoursedb_v02`.`DiscourseRelation_Type` (`idDiscourseRelation_Type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DiscourseRelation_Annotation1`
    FOREIGN KEY (`Annotation_idAnnotation`)
    REFERENCES `discoursedb_v02`.`Annotation` (`idAnnotation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Reply_Contribution1_idx` ON `discoursedb_v02`.`DiscourseRelation` (`sourceContributionId` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Reply_Contribution2_idx` ON `discoursedb_v02`.`DiscourseRelation` (`targetContributionId` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Reply_Reply_Type1_idx` ON `discoursedb_v02`.`DiscourseRelation` (`discourseRelation_TypeID` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_DiscourseRelation_Annotation1_idx` ON `discoursedb_v02`.`DiscourseRelation` (`Annotation_idAnnotation` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `discoursedb_v02`.`DiscoursePart_Relation_Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discoursedb_v02`.`DiscoursePart_Relation_Type` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `discoursedb_v02`.`DiscoursePart_Relation_Type` (
  `idDiscoursePart_Relation_Type` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(200) NULL,
  PRIMARY KEY (`idDiscoursePart_Relation_Type`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `discoursedb_v02`.`DiscoursePart_Relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discoursedb_v02`.`DiscoursePart_Relation` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `discoursedb_v02`.`DiscoursePart_Relation` (
  `idEmbedding` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sourceDiscoursePartID` BIGINT UNSIGNED NOT NULL,
  `targetDiscoursePartID` BIGINT UNSIGNED NOT NULL,
  `startTime` DATETIME NULL,
  `endTime` DATETIME NULL,
  `Annotation_idAnnotation` BIGINT UNSIGNED NULL,
  `DiscoursePart_Relation_Type_idDiscoursePart_Relation_Type` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idEmbedding`),
  CONSTRAINT `fk_Embedding_DiscoursePart1`
    FOREIGN KEY (`sourceDiscoursePartID`)
    REFERENCES `discoursedb_v02`.`DiscoursePart` (`idDiscoursePart`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Embedding_DiscoursePart2`
    FOREIGN KEY (`targetDiscoursePartID`)
    REFERENCES `discoursedb_v02`.`DiscoursePart` (`idDiscoursePart`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Embedding_Annotation1`
    FOREIGN KEY (`Annotation_idAnnotation`)
    REFERENCES `discoursedb_v02`.`Annotation` (`idAnnotation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DiscoursePart_Relation_DiscoursePart_Relation_Type1`
    FOREIGN KEY (`DiscoursePart_Relation_Type_idDiscoursePart_Relation_Type`)
    REFERENCES `discoursedb_v02`.`DiscoursePart_Relation_Type` (`idDiscoursePart_Relation_Type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Embedding_DiscoursePart1_idx` ON `discoursedb_v02`.`DiscoursePart_Relation` (`sourceDiscoursePartID` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Embedding_DiscoursePart2_idx` ON `discoursedb_v02`.`DiscoursePart_Relation` (`targetDiscoursePartID` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Embedding_Annotation1_idx` ON `discoursedb_v02`.`DiscoursePart_Relation` (`Annotation_idAnnotation` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_DiscoursePart_Relation_DiscoursePart_Relation_Type1_idx` ON `discoursedb_v02`.`DiscoursePart_Relation` (`DiscoursePart_Relation_Type_idDiscoursePart_Relation_Type` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `discoursedb_v02`.`Feature_Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discoursedb_v02`.`Feature_Type` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `discoursedb_v02`.`Feature_Type` (
  `feat_type_ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL,
  `datatype` VARCHAR(200) NULL,
  `description` VARCHAR(200) NULL,
  PRIMARY KEY (`feat_type_ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `discoursedb_v02`.`Annotation_Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discoursedb_v02`.`Annotation_Type` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `discoursedb_v02`.`Annotation_Type` (
  `idAnnotation_Type` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(200) NULL,
  `isEntityAnnotation` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idAnnotation_Type`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `discoursedb_v02`.`DiscourseDB`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discoursedb_v02`.`DiscourseDB` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `discoursedb_v02`.`DiscourseDB` (
  `idDiscourseDB` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `schema_version` VARCHAR(200) NOT NULL,
  `startTime` DATETIME NOT NULL,
  `endTime` DATETIME NULL,
  PRIMARY KEY (`idDiscourseDB`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `discoursedb_v02`.`Annotation_Instance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discoursedb_v02`.`Annotation_Instance` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `discoursedb_v02`.`Annotation_Instance` (
  `idSpan_Annotation` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `beginOffset` INT NULL,
  `endOffset` INT NULL,
  `coveredText` TEXT NULL,
  `Annotation_Instance_idAnnotation` BIGINT UNSIGNED NOT NULL,
  `startTime` DATETIME NULL,
  `endTime` DATETIME NULL,
  `Annotation_Type_idAnnotation_Type` BIGINT UNSIGNED NOT NULL,
  `DiscourseDB_idDiscourseDB` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idSpan_Annotation`),
  CONSTRAINT `fk_Annotation_Instance_Annotation1`
    FOREIGN KEY (`Annotation_Instance_idAnnotation`)
    REFERENCES `discoursedb_v02`.`Annotation` (`idAnnotation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Annotation_Instance_Annotation_Type1`
    FOREIGN KEY (`Annotation_Type_idAnnotation_Type`)
    REFERENCES `discoursedb_v02`.`Annotation_Type` (`idAnnotation_Type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Annotation_Instance_DiscourseDB1`
    FOREIGN KEY (`DiscourseDB_idDiscourseDB`)
    REFERENCES `discoursedb_v02`.`DiscourseDB` (`idDiscourseDB`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Annotation_Instance_Annotation1_idx` ON `discoursedb_v02`.`Annotation_Instance` (`Annotation_Instance_idAnnotation` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Annotation_Instance_Annotation_Type1_idx` ON `discoursedb_v02`.`Annotation_Instance` (`Annotation_Type_idAnnotation_Type` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Annotation_Instance_DiscourseDB1_idx` ON `discoursedb_v02`.`Annotation_Instance` (`DiscourseDB_idDiscourseDB` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `discoursedb_v02`.`Feature_Instance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discoursedb_v02`.`Feature_Instance` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `discoursedb_v02`.`Feature_Instance` (
  `feat_inst_ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `feat_type_ID` BIGINT UNSIGNED NOT NULL,
  `value` TEXT NULL,
  `Annotation_Instance_idSpan_Annotation` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`feat_inst_ID`),
  CONSTRAINT `fk_Feature_Inst_Feature_Type1`
    FOREIGN KEY (`feat_type_ID`)
    REFERENCES `discoursedb_v02`.`Feature_Type` (`feat_type_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Feature_Annotation_Instance1`
    FOREIGN KEY (`Annotation_Instance_idSpan_Annotation`)
    REFERENCES `discoursedb_v02`.`Annotation_Instance` (`idSpan_Annotation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Feature_Inst_Feature_Type1_idx` ON `discoursedb_v02`.`Feature_Instance` (`feat_type_ID` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Feature_Annotation_Instance1_idx` ON `discoursedb_v02`.`Feature_Instance` (`Annotation_Instance_idSpan_Annotation` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `discoursedb_v02`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discoursedb_v02`.`User` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `discoursedb_v02`.`User` (
  `idUser` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `realname` VARCHAR(200) NULL,
  `username` VARCHAR(200) NULL,
  `email` VARCHAR(200) NULL,
  `location` VARCHAR(200) NULL,
  `language` VARCHAR(200) NULL,
  `Annotation_idAnnotation` BIGINT UNSIGNED NULL,
  PRIMARY KEY (`idUser`),
  CONSTRAINT `fk_User_Annotation1`
    FOREIGN KEY (`Annotation_idAnnotation`)
    REFERENCES `discoursedb_v02`.`Annotation` (`idAnnotation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

SHOW WARNINGS;
CREATE INDEX `fk_User_Annotation1_idx` ON `discoursedb_v02`.`User` (`Annotation_idAnnotation` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `discoursedb_v02`.`Group_Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discoursedb_v02`.`Group_Type` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `discoursedb_v02`.`Group_Type` (
  `idGroup_Type` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(200) NULL,
  PRIMARY KEY (`idGroup_Type`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `discoursedb_v02`.`Group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discoursedb_v02`.`Group` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `discoursedb_v02`.`Group` (
  `idGroup` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL,
  `startTime` DATETIME NOT NULL COMMENT '	',
  `endTime` DATETIME NULL,
  `Group_Type_idGroup_Type` BIGINT UNSIGNED NOT NULL,
  `Annotation_idAnnotation` BIGINT UNSIGNED NULL,
  PRIMARY KEY (`idGroup`),
  CONSTRAINT `fk_Group_Group_Type1`
    FOREIGN KEY (`Group_Type_idGroup_Type`)
    REFERENCES `discoursedb_v02`.`Group_Type` (`idGroup_Type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Group_Annotation1`
    FOREIGN KEY (`Annotation_idAnnotation`)
    REFERENCES `discoursedb_v02`.`Annotation` (`idAnnotation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Group_Group_Type1_idx` ON `discoursedb_v02`.`Group` (`Group_Type_idGroup_Type` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Group_Annotation1_idx` ON `discoursedb_v02`.`Group` (`Annotation_idAnnotation` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `discoursedb_v02`.`User_memberof_Group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discoursedb_v02`.`User_memberof_Group` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `discoursedb_v02`.`User_memberof_Group` (
  `User_idUser` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Group_idGroup` BIGINT UNSIGNED NOT NULL,
  `startTime` DATETIME NULL,
  `endTime` DATETIME NULL,
  `Annotation_idAnnotation` BIGINT UNSIGNED NULL,
  PRIMARY KEY (`User_idUser`, `Group_idGroup`),
  CONSTRAINT `fk_User_has_Group_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `discoursedb_v02`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Group_Group1`
    FOREIGN KEY (`Group_idGroup`)
    REFERENCES `discoursedb_v02`.`Group` (`idGroup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_memberof_Group_Annotation1`
    FOREIGN KEY (`Annotation_idAnnotation`)
    REFERENCES `discoursedb_v02`.`Annotation` (`idAnnotation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

SHOW WARNINGS;
CREATE INDEX `fk_User_has_Group_Group1_idx` ON `discoursedb_v02`.`User_memberof_Group` (`Group_idGroup` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_User_has_Group_User1_idx` ON `discoursedb_v02`.`User_memberof_Group` (`User_idUser` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_User_memberof_Group_Annotation1_idx` ON `discoursedb_v02`.`User_memberof_Group` (`Annotation_idAnnotation` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `discoursedb_v02`.`Contribution_partOf_DiscoursePart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discoursedb_v02`.`Contribution_partOf_DiscoursePart` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `discoursedb_v02`.`Contribution_partOf_DiscoursePart` (
  `Contribution_idContribution` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `DiscoursePart_idDiscoursePart` BIGINT UNSIGNED NOT NULL,
  `startTime` DATETIME NULL,
  `endTime` DATETIME NULL,
  `Annotation_idAnnotation` BIGINT UNSIGNED NULL,
  PRIMARY KEY (`Contribution_idContribution`, `DiscoursePart_idDiscoursePart`),
  CONSTRAINT `fk_Contribution_has_DiscoursePart_Contribution1`
    FOREIGN KEY (`Contribution_idContribution`)
    REFERENCES `discoursedb_v02`.`Contribution` (`idContribution`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contribution_has_DiscoursePart_DiscoursePart1`
    FOREIGN KEY (`DiscoursePart_idDiscoursePart`)
    REFERENCES `discoursedb_v02`.`DiscoursePart` (`idDiscoursePart`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contribution_partOf_DiscoursePart_Annotation1`
    FOREIGN KEY (`Annotation_idAnnotation`)
    REFERENCES `discoursedb_v02`.`Annotation` (`idAnnotation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Contribution_has_DiscoursePart_DiscoursePart1_idx` ON `discoursedb_v02`.`Contribution_partOf_DiscoursePart` (`DiscoursePart_idDiscoursePart` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Contribution_has_DiscoursePart_Contribution1_idx` ON `discoursedb_v02`.`Contribution_partOf_DiscoursePart` (`Contribution_idContribution` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Contribution_partOf_DiscoursePart_Annotation1_idx` ON `discoursedb_v02`.`Contribution_partOf_DiscoursePart` (`Annotation_idAnnotation` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `discoursedb_v02`.`Discourse_has_DiscoursePart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discoursedb_v02`.`Discourse_has_DiscoursePart` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `discoursedb_v02`.`Discourse_has_DiscoursePart` (
  `Discourse_idDiscourse` BIGINT UNSIGNED NOT NULL,
  `Discourse_Collection_col_ID` BIGINT UNSIGNED NOT NULL,
  `startTime` DATETIME NULL,
  `endTime` DATETIME NULL,
  `Annotation_idAnnotation` BIGINT UNSIGNED NULL,
  PRIMARY KEY (`Discourse_idDiscourse`, `Discourse_Collection_col_ID`),
  CONSTRAINT `fk_Discourse_has_DiscoursePart_Discourse1`
    FOREIGN KEY (`Discourse_idDiscourse`)
    REFERENCES `discoursedb_v02`.`Discourse` (`idDiscourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Discourse_has_DiscoursePart_DiscoursePart1`
    FOREIGN KEY (`Discourse_Collection_col_ID`)
    REFERENCES `discoursedb_v02`.`DiscoursePart` (`idDiscoursePart`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Discourse_has_DiscoursePart_Annotation1`
    FOREIGN KEY (`Annotation_idAnnotation`)
    REFERENCES `discoursedb_v02`.`Annotation` (`idAnnotation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Discourse_has_DiscoursePart_DiscoursePart1_idx` ON `discoursedb_v02`.`Discourse_has_DiscoursePart` (`Discourse_Collection_col_ID` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Discourse_has_DiscoursePart_Discourse1_idx` ON `discoursedb_v02`.`Discourse_has_DiscoursePart` (`Discourse_idDiscourse` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Discourse_has_DiscoursePart_Annotation1_idx` ON `discoursedb_v02`.`Discourse_has_DiscoursePart` (`Annotation_idAnnotation` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `discoursedb_v02`.`Audience_Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discoursedb_v02`.`Audience_Type` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `discoursedb_v02`.`Audience_Type` (
  `idAudience_Type` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(200) NULL,
  PRIMARY KEY (`idAudience_Type`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `discoursedb_v02`.`Audience`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discoursedb_v02`.`Audience` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `discoursedb_v02`.`Audience` (
  `idAudience` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Audience_Type_idAudience_Type` BIGINT UNSIGNED NOT NULL,
  `Annotation_idAnnotation` BIGINT UNSIGNED NULL,
  PRIMARY KEY (`idAudience`),
  CONSTRAINT `fk_Audience_Audience_Type1`
    FOREIGN KEY (`Audience_Type_idAudience_Type`)
    REFERENCES `discoursedb_v02`.`Audience_Type` (`idAudience_Type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Audience_Annotation1`
    FOREIGN KEY (`Annotation_idAnnotation`)
    REFERENCES `discoursedb_v02`.`Annotation` (`idAnnotation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Audience_Audience_Type1_idx` ON `discoursedb_v02`.`Audience` (`Audience_Type_idAudience_Type` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Audience_Annotation1_idx` ON `discoursedb_v02`.`Audience` (`Annotation_idAnnotation` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `discoursedb_v02`.`Audience_has_User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discoursedb_v02`.`Audience_has_User` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `discoursedb_v02`.`Audience_has_User` (
  `Audience_idAudience` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `User_idUser` BIGINT UNSIGNED NOT NULL,
  `startTime` VARCHAR(45) NOT NULL,
  `endTime` VARCHAR(45) NULL,
  `Annotation_idAnnotation` BIGINT UNSIGNED NULL,
  PRIMARY KEY (`Audience_idAudience`, `User_idUser`),
  CONSTRAINT `fk_Audience_has_User_Audience1`
    FOREIGN KEY (`Audience_idAudience`)
    REFERENCES `discoursedb_v02`.`Audience` (`idAudience`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Audience_has_User_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `discoursedb_v02`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Audience_has_User_Annotation1`
    FOREIGN KEY (`Annotation_idAnnotation`)
    REFERENCES `discoursedb_v02`.`Annotation` (`idAnnotation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Audience_has_User_User1_idx` ON `discoursedb_v02`.`Audience_has_User` (`User_idUser` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Audience_has_User_Audience1_idx` ON `discoursedb_v02`.`Audience_has_User` (`Audience_idAudience` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Audience_has_User_Annotation1_idx` ON `discoursedb_v02`.`Audience_has_User` (`Annotation_idAnnotation` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `discoursedb_v02`.`Audience_has_Group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discoursedb_v02`.`Audience_has_Group` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `discoursedb_v02`.`Audience_has_Group` (
  `Audience_idAudience` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Group_idGroup` BIGINT UNSIGNED NOT NULL,
  `startTime` DATETIME NULL,
  `endTime` DATETIME NULL,
  `Annotation_idAnnotation` BIGINT UNSIGNED NULL,
  PRIMARY KEY (`Audience_idAudience`, `Group_idGroup`),
  CONSTRAINT `fk_Audience_has_Group_Audience1`
    FOREIGN KEY (`Audience_idAudience`)
    REFERENCES `discoursedb_v02`.`Audience` (`idAudience`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Audience_has_Group_Group1`
    FOREIGN KEY (`Group_idGroup`)
    REFERENCES `discoursedb_v02`.`Group` (`idGroup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Audience_has_Group_Annotation1`
    FOREIGN KEY (`Annotation_idAnnotation`)
    REFERENCES `discoursedb_v02`.`Annotation` (`idAnnotation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Audience_has_Group_Group1_idx` ON `discoursedb_v02`.`Audience_has_Group` (`Group_idGroup` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Audience_has_Group_Audience1_idx` ON `discoursedb_v02`.`Audience_has_Group` (`Audience_idAudience` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Audience_has_Group_Annotation1_idx` ON `discoursedb_v02`.`Audience_has_Group` (`Annotation_idAnnotation` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `discoursedb_v02`.`Contribution_has_Audience`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discoursedb_v02`.`Contribution_has_Audience` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `discoursedb_v02`.`Contribution_has_Audience` (
  `Contribution_idContribution` BIGINT UNSIGNED NOT NULL,
  `Audience_idAudience` BIGINT UNSIGNED NOT NULL,
  `Annotation_idAnnotation` BIGINT UNSIGNED NULL,
  `startTime` DATETIME NULL,
  `endTime` DATETIME NULL,
  PRIMARY KEY (`Contribution_idContribution`, `Audience_idAudience`),
  CONSTRAINT `fk_Contribution_has_Audience_Contribution1`
    FOREIGN KEY (`Contribution_idContribution`)
    REFERENCES `discoursedb_v02`.`Contribution` (`idContribution`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contribution_has_Audience_Audience1`
    FOREIGN KEY (`Audience_idAudience`)
    REFERENCES `discoursedb_v02`.`Audience` (`idAudience`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contribution_has_Audience_Annotation1`
    FOREIGN KEY (`Annotation_idAnnotation`)
    REFERENCES `discoursedb_v02`.`Annotation` (`idAnnotation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Contribution_has_Audience_Audience1_idx` ON `discoursedb_v02`.`Contribution_has_Audience` (`Audience_idAudience` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Contribution_has_Audience_Contribution1_idx` ON `discoursedb_v02`.`Contribution_has_Audience` (`Contribution_idContribution` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Contribution_has_Audience_Annotation1_idx` ON `discoursedb_v02`.`Contribution_has_Audience` (`Annotation_idAnnotation` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `discoursedb_v02`.`Context_Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discoursedb_v02`.`Context_Type` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `discoursedb_v02`.`Context_Type` (
  `idContext_Type` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(200) NULL,
  PRIMARY KEY (`idContext_Type`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `discoursedb_v02`.`Context`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discoursedb_v02`.`Context` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `discoursedb_v02`.`Context` (
  `idContext` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `startTime` DATETIME NULL,
  `endTime` DATETIME NULL,
  `firstRevisionID` BIGINT UNSIGNED NULL,
  `currentRevisionID` BIGINT UNSIGNED NULL,
  `Context_Type_idContext_Type` BIGINT UNSIGNED NULL,
  `Annotation_idAnnotation` BIGINT UNSIGNED NULL,
  PRIMARY KEY (`idContext`),
  CONSTRAINT `fk_Context_Content1`
    FOREIGN KEY (`firstRevisionID`)
    REFERENCES `discoursedb_v02`.`Content` (`idRevision`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Context_Content2`
    FOREIGN KEY (`currentRevisionID`)
    REFERENCES `discoursedb_v02`.`Content` (`idRevision`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Context_Context_Type1`
    FOREIGN KEY (`Context_Type_idContext_Type`)
    REFERENCES `discoursedb_v02`.`Context_Type` (`idContext_Type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Context_Annotation1`
    FOREIGN KEY (`Annotation_idAnnotation`)
    REFERENCES `discoursedb_v02`.`Annotation` (`idAnnotation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Context_Content1_idx` ON `discoursedb_v02`.`Context` (`firstRevisionID` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Context_Content2_idx` ON `discoursedb_v02`.`Context` (`currentRevisionID` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Context_Context_Type1_idx` ON `discoursedb_v02`.`Context` (`Context_Type_idContext_Type` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Context_Annotation1_idx` ON `discoursedb_v02`.`Context` (`Annotation_idAnnotation` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `discoursedb_v02`.`Contribution_has_Context`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discoursedb_v02`.`Contribution_has_Context` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `discoursedb_v02`.`Contribution_has_Context` (
  `Contribution_idContribution` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Context_idContext` BIGINT UNSIGNED NOT NULL,
  `startTime` DATETIME NULL,
  `endTime` DATETIME NULL,
  `Annotation_idAnnotation` BIGINT UNSIGNED NULL,
  PRIMARY KEY (`Contribution_idContribution`, `Context_idContext`),
  CONSTRAINT `fk_Contribution_has_Context_Contribution1`
    FOREIGN KEY (`Contribution_idContribution`)
    REFERENCES `discoursedb_v02`.`Contribution` (`idContribution`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contribution_has_Context_Context1`
    FOREIGN KEY (`Context_idContext`)
    REFERENCES `discoursedb_v02`.`Context` (`idContext`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contribution_has_Context_Annotation1`
    FOREIGN KEY (`Annotation_idAnnotation`)
    REFERENCES `discoursedb_v02`.`Annotation` (`idAnnotation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Contribution_has_Context_Context1_idx` ON `discoursedb_v02`.`Contribution_has_Context` (`Context_idContext` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Contribution_has_Context_Contribution1_idx` ON `discoursedb_v02`.`Contribution_has_Context` (`Contribution_idContribution` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Contribution_has_Context_Annotation1_idx` ON `discoursedb_v02`.`Contribution_has_Context` (`Annotation_idAnnotation` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `discoursedb_v02`.`Content_Interaction_Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discoursedb_v02`.`Content_Interaction_Type` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `discoursedb_v02`.`Content_Interaction_Type` (
  `idContent_Interaction_Type` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`idContent_Interaction_Type`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `discoursedb_v02`.`Content_Interaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discoursedb_v02`.`Content_Interaction` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `discoursedb_v02`.`Content_Interaction` (
  `User_idUser` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Content_idRevision` BIGINT UNSIGNED NOT NULL,
  `startTime` DATETIME NULL,
  `endTime` DATETIME NULL,
  `Content_Interaction_Type_idContent_Interaction_Type` BIGINT UNSIGNED NOT NULL,
  `Annotation_idAnnotation` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`User_idUser`, `Content_idRevision`),
  CONSTRAINT `fk_User_has_Content_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `discoursedb_v02`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Content_Content1`
    FOREIGN KEY (`Content_idRevision`)
    REFERENCES `discoursedb_v02`.`Content` (`idRevision`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Content_Interaction_Content_Interaction_Type1`
    FOREIGN KEY (`Content_Interaction_Type_idContent_Interaction_Type`)
    REFERENCES `discoursedb_v02`.`Content_Interaction_Type` (`idContent_Interaction_Type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Content_Interaction_Annotation1`
    FOREIGN KEY (`Annotation_idAnnotation`)
    REFERENCES `discoursedb_v02`.`Annotation` (`idAnnotation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

SHOW WARNINGS;
CREATE INDEX `fk_User_has_Content_Content1_idx` ON `discoursedb_v02`.`Content_Interaction` (`Content_idRevision` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_User_has_Content_User1_idx` ON `discoursedb_v02`.`Content_Interaction` (`User_idUser` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Content_Interaction_Content_Interaction_Type1_idx` ON `discoursedb_v02`.`Content_Interaction` (`Content_Interaction_Type_idContent_Interaction_Type` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_Content_Interaction_Annotation1_idx` ON `discoursedb_v02`.`Content_Interaction` (`Annotation_idAnnotation` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `discoursedb_v02`.`DiscourseDB`
-- -----------------------------------------------------
START TRANSACTION;
USE `discoursedb_v02`;
INSERT INTO `discoursedb_v02`.`DiscourseDB` (`idDiscourseDB`, `schema_version`, `startTime`, `endTime`) VALUES (NULL, '0.2', 'NOW()', NULL);

COMMIT;

